(global-set-key (kbd "M--") '(lambda ()
                                 (interactive)
                                 (if (boundp 'tabbar-version)
                                         (tabbar-backward-tab)
                                     (previous-buffer))))
(global-set-key (kbd "M-=") '(lambda ()
                                 (interactive)
                                 (if (boundp 'tabbar-version)
                                         (tabbar-forward-tab)
j                                     (next-buffer))))
