(require 'org)
(set-face-attribute 'org-level-1 nil :foreground "#FFFF00")
(set-face-attribute 'org-level-2 nil :foreground "#9999ff")
(set-face-attribute 'org-level-3 nil :foreground "#dd2200")
(set-face-attribute 'org-level-4 nil :foreground "#119900")
