(defun fphp-resolve-class-namespace (file)
  (setq file (replace-regexp-in-string ".php" "" file))
  (setq path (split-string file "/"))
  (setq srcpos (cl-position "src" path :test 'equal))
  (if (not srcpos)
      (setq srcpos (cl-position "tests" path :test 'equal)))
  (setq slicedpath (-slice path (+ srcpos 1) -1))
  (mapconcat 'identity slicedpath "\\")
  )

(defun fphp-resolve-class-name (file)
  (setq path (split-string file "/"))
  (first (last path))
  )

(defun fphp-create-class-body (file)
  (setq body "")
  (setq body (concat body "<?php\n\n"))
  (setq body (concat body "declare(strict_types = 1);\n\n"))
  (setq body (concat body "namespace " (fphp-resolve-class-namespace file) ";\n\n"))
  (setq body (concat body "class " (fphp-resolve-class-name file) "\n"))
  (setq body (concat body "{\n\s\s\s\s\n}\n"))
  )

(defun fphp-fill-current-file-body ()
  (interactive)
  (insert (fphp-create-class-body (buffer-file-name))))

(lambda ()
  (setq testfile "src/EatPoint/Application/Security/Registration/Command/Handler/InviteManagerHandler")
  (setq testfile "/home/filip/Projects/eatpoint/backend/tests/functional/Registraion/ManagerRegistrationTest.php")
  (setq file testfile)
  (message (fphp-create-class-body testfile))
  (message (fphp-resolve-class-namespace testfile))
)
